models:
  - name: int_gsheet_sales__customer_favorite_product
    description: This model identifies the favorite product for each customer based on the total quantity purchased. 
      It uses a window function to rank products by quantity purchased for each customer and selects 
      the top-ranking product. If multiple products have the same quantity, one is arbitrarily chosen. 
      This model is useful for customer analysis and personalization strategies, such as recommending 
      products or targeting promotions based on customer preferences.

    columns:
      - name: customer_id
        description: Unique identifier for the customer.
      - name: favorite_product_id
        description: Unique identifier for the product that was purchased the most by the customer.


  - name: int_gsheet_sales__customers_performance
    description: This model provides an aggregated view of customer performance, including their personal information and key metrics related to their purchasing behavior. 
      It helps identify the most active customers, analyze their lifecycle, and gain a deeper understanding of their product and store preferences. 

    columns:
      - name: customer_id
        description: Unique identifier for the customer.
        tests:
          - unique
          - not_null
      - name: customer_name
        description: Full name of the customer (concatenation of first and last names).
      - name: customer_email
        description: Email address of the customer.
      - name: total_orders
        description: Total number of orders placed by the customer.
      - name: total_spent
        description: Total amount spent by the customer.
      - name: last_order_date
        description: Date of the customer's most recent order.
      - name: first_order_date
        description: Date of the customer's first order.
      - name: customer_lifetime_days
        description: Customer's lifecycle (difference in days between the first and last orders).
      - name: avg_order_value
        description: Average value of the customer's orders.
      - name: unique_products_purchased
        description: Number of unique products purchased by the customer.
      - name: stores_visited
        description: Number of distinct stores visited by the customer.


models:
  - name: product_sales_performance
    description: This model aggregates sales performance metrics for each product by month. It provides insights into sales trends, product popularity, and overall performance. Metrics include total sales amount, units sold, number of orders, and product details such as brand, category, and price.
    columns:
      - name: product_id
        description: Unique identifier of the product.
        tests:
          - not_null
      - name: product_name
        description: Name of the product.
      - name: brand_name
        description: Brand associated with the product.
      - name: model_year
        description: Model year of the product.
      - name: product_price
        description: Price of the product.
      - name: category_name
        description: Category to which the product belongs.
      - name: sales_month
        description: Month and year of the aggregated sales data.
      - name: total_sales
        description: Total sales amount generated by the product during the given month.
      - name: total_units_sold
        description: Total quantity of units sold for the product during the given month.
      - name: total_orders
        description: Total number of distinct orders that included the product during the given month.


  - name: int_gsheet_sales__monthly_sales_performance
    description: This model aggregates sales data by store, product category and product name on a monthly basis. 
      It provides key metrics to analyze store performance, product popularity, and customer engagement. 
      This model is essential for understanding trends and making data-driven decisions to optimize sales and operations. 

    columns:
      - name: store_id
        description: Unique identifier for the store.
        tests:
          - not_null
      - name: store_name
        description: Name of the store.
      - name: category_name
        description: Name of the product category.
      - name: product_name
        description: Name of the product.
      - name: sales_month
        description: Month in which the sales occurred (truncated to the first day of the month).
      - name: total_sales
        description: Total revenue generated from sales.
      - name: total_units_sold
        description: Total number of units sold for the product.
      - name: avg_price_per_unit
        description: Average selling price per unit.
      - name: total_orders
        description: Total number of orders that included the product.
      - name: unique_customers
        description: Number of unique customers who purchased the product.


  - name: int_gsheet_sales__stores_performance
    description: This model provides key performance metrics for each store, offering insights into store operations, 
      customer engagement, and product sales over time. It aggregates data at the store level, helping stakeholders 
      understand the overall performance and trends for each location. 

    columns:
      - name: store_id
        description: Unique identifier for the store.
        tests:
          - unique
          - not_null
      - name: store_name
        description: Name of the store.
      - name: store_city
        description: City where the store is located.
      - name: store_state
        description: State where the store is located.
      - name: total_orders
        description: Total number of orders placed at the store.
      - name: total_revenue
        description: Total revenue generated by the store.
      - name: avg_order_value
        description: Average value of an order at the store.
      - name: unique_customers
        description: Number of unique customers who made purchases at the store.
      - name: unique_products_sold
        description: Number of unique products sold at the store.
      - name: last_order_date
        description: Date of the most recent order placed at the store.
      - name: first_order_date
        description: Date of the first recorded order placed at the store.
      - name: store_lifetime_days
        description: Number of days between the first and the most recent order at the store.
      - name: total_staff
        description: Total number of staff members associated with the store.